version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - '${DBPORT}:${DBPORT}'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - '${APIPORT}:${APIPORT}'
    depends_on:
      - db
    links:
      - db 
volumes:
  db:
    driver: local